# Generated by Django 5.2.17 on 2026-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('problem_raised', 'Problem Raised'), ('assigned', 'Assigned'), ('problem_initiated', 'Problem Initiated'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='problem_raised', max_length=20),
        ),
    ]
