# Generated by Django 5.2.17 on 2026-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('civilian', 'Civilian'), ('department_staff', 'Department Staff')], default='civilian', max_length=20),
        ),
    ]
